import Head from "next/head";
import "tailwindcss/tailwind.css";
import { FooterMenu } from "../components/layouts/FooterMenu";
import { Header } from "../components/layouts/Header";
import { Profile } from "../components/layouts/Profile";

export default function Home() {
  return (
    <div>
      <Head>
        <title>biet-new</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Profile />
      <FooterMenu />
    </div>
  );
}
